package es.serversurvival.v1.bolsa.activosinfo.vervalores.acciones;

import java.util.HashMap;
import java.util.Map;

public final class TodasAccionesVerValores {
    public static final Map<String, String> accciones;

    static {
        accciones = new HashMap<>(){{
            put("ATVI", "Activision");
            put("ADBE", "Adobe");
            put("GOOG", "Google");
            put("AMZN", "Amazon");
            put("AMD", "AMD");
            put("AAPL", "Apple");
            put("T", "AT&T");
            put("AXP", "American Express");
            put("BAC", "Bank of America");
            put("BRK.B", "Berkshire Hathaway");
            put("BA", "Boeing");
            put("CAJ", "Canon");
            put("KO", "Cocacola");
            put("DELL", "Dell");
            put("DISCA", "Discovery");
            put("DBX", "Dropbox");
            put("ETFC", "Ebay");
            put("FDX", "FedEx");
            put("FL", "FootLocker");
            put("F", "Ford");
            put("GE", "General electric");
            put("GPRO", "Gopro");
            put("HPQ", "HP");
            put("IBM", "IBM");
            put("INTC", "Intel");
            put("KHC", "Heinz");
            put("MCD", "MacDonalds");
            put("MSFT", "Microsoft");
            put("NFLX", "Netflix");
            put("ORCL", "Oracle");
            put("PYPL", "PayPal");
            put("YUM", "YUM (Tacobell, KFC y PizzaHut)");
            put("LUV", "South West");
            put("SPOT", "Spotify");
            put("SBUX", "StartBucks");
            put("TSLA", "Tesla");
            put("TWTR", "Twitter");
            put("UBER", "Uber");
            put("V", "Visa");
            put("BABA", "Alibaba");
            put("DAL", "Delta");
            put("META", "Facebook");
            put("SAN", "Santander!!");
            put("NVDA", "Nvdia");
            put("HLT", "Hilton");
            put("WM", "Disney");
            put("WMT", "Wallmart");
            put("RCL", "RCruises");
            put("XRX", "Xerox");
            put("WFC", "Wells Fargo");
            put("SHOP", "Shopify");
            put("SNAP","Snapchat");
            put("NKE", "Nike");
            put("VZ", "Verizon");
            put("TM","Toyota");
            put("TRIP", "Trip advisor");
            put("TMUS","T-Movile");
            put("QCOM","Qualcomm");
            put("PM","Philip Morris");
            put("NDAQ","NASDAQ");
            put("MSI","Motorola");
            put("MA","Mastercard");
            put("JPM","JP Morgan");
            put("HMC","Honda");
            put("GME","GameStop");
            put("RACE","Ferrari");
            put("TEF","Telefonica");
            put("REPYY","Repsol");
            put("BKNG","Booking holdings");
            put("AAL","American airlines");
            put("GHC","Whasington post");
            put("APA","Apache");
            put("CTSH","Cognizant");
            put("PINS","Pinerest");
            put("ZM","Zoom");
            put("CVX","Chevron");
            put("CSCO","Cisco");
            put("PEP","Pepsi");
            put("TSM", "Taiwan semiconductor manufacturing ");
            put("JNJ", "Johnson&Johnson");
            put("MCO", "Moodys corporation");
            put("FNMA", "Fannie Mae");
            put("AZN", "AstraZeneca");
            put("SAP", "SAP");
            put("LOGI", "Logitech");
        }};
    }
}
