name: PixelCoins
main: es.serversurvival.config.Pixelcoin
version: 1.1
api-version: "1.14"
commands:
  dinero:
    description: Comando para ver tu dinero
    usage: /<command>
  pagar:
    description: pagar dinero a otro jugador
    usage: /<command> <nombre jugador> <cantidad>
  topricos:
    description: mostrar los 3 más ricos del servidor
    usage: /<command>
  toppobres:
    description: mostrar los 3 más pobres del servidor
    usage: /<command>
  verdinero:
    description: ver pixelcoins de los jugadores
    usage: /<command> <jugador>
  listaOfertas:
    description: ver todos los objetos que tienes en la tienda
    usage: /<command>
  tienda:
    description: Comando para ver la tienda
    usage: /<command>
  vender:
    description: Comando para vender un objeto en la mano
    usage: /<command> <precioa vender /item>
  ayuda:
    description: mostrar ayuda
    usage: /<command> <tipoAyuda>
  estadisticas:
    description: Ver todos tus objetos vendidos, gastos, ingresos y beneficios
    usage: /<command>
  topvendedores:
    description: Ver los 3 jugadores que mas han vendido en la tienda y le han pagado
    usage: /<command>