package es.serversurvival.v2.pixelcoins.transacciones;

public enum TipoTransaccion {
    JUGADORES_PAGO,
    JUGADORES_CAMBIO_INGRESAR_ITEM,
    JUGADORES_CAMBIO_SACAR_ITEM,
    JUGADORES_CAMBIO_SACAR_MAX_ITEM,

    DEUDAS_PRIMER_DESEMBOLSO,
    DEUDAS_CUOTA,
    DEUDAS_PAGO_COMPLETO
}
