package es.serversurvival.v2.pixelcoins.transacciones;

public enum TipoTransaccion {
    JUGADORES_PAGO,
    JUGADORES_CAMBIO_INGRESAR_ITEM,
    JUGADORES_CAMBIO_SACAR_ITEM,
    JUGADORES_CAMBIO_SACAR_MAX_ITEM,

    DEUDAS_PRIMER_DESEMBOLSO,
    DEUDAS_CUOTA,
    DEUDAS_PAGO_COMPLETO,
    DEUDAS_MERCADO_SECUNDARIO_COMPRA,
    DEUDAS_MERCADO_PRIMARIO_COMPRA,

    EMPRESAS_COMPRA_SERVICIO,
    EMPRESAS_CERRAR,
    EMPRESAS_DEPOSITAR,
    EMPRESAS_DIVIDENDO,
    EMPRESAS_SUELDO,
    EMPRESAS_SACAR
}
