package es.serversurvival.mySQL.enums;

public enum TipoTransaccion {
    BASEDATOS_CAMBIAR_NOMBRE,

    TIENDA_VENTA,

    JUGADOR_PAGO_MANUAL,
    JUGADOR_VENDER,

    WITHERS_INGRESAR,
    WITHERS_SACAR,
    WITHERS_SACARMAX,

    EMPRESA_BORRAR,
    EMPRESA_DEPOSITAR,
    EMPRESA_SACAR,
    EMPRESA_VENTA,
    EMPRESA_PAGAR_SALARIO,
    EMPRESA_COMPRAR_SERVICIO,

    DEUDAS_PAGAR_DEUDAS,
    DEUDAS_PAGAR_TODADEUDA,
    DEUDAS_PRIMERPAGO,

    BOLSA_COMPRA,
    BOLSA_CORTO_VENTA,
    BOLSA_CORTO_COMPRA,
    BOLSA_VENTA,
    BOLSA_DIVIDENDO,
    
    WEB_TRANSFERENCIA,
    WEB_COMPRAACCION,
    WEB_VENTA_ACCION,
    WEB_PAGAR_DEUDA,
    WEB_BORRAR_EMPRESA,
    WEB_CREAR_EMPRESA
}
