name: PixelCoins
main: es.serversurvival.Pixelcoin
version: 11.0
api-version: "1.20"
commands:
  lootbox:
    description: Ver los lootboxes
    usage: /<command>
  retos:
    description: Ver los retos
    usage: /<command>
  transacciones:
    description: Ver los ultimos movimientos de pixelcoins que has hecho
    usage: /<command>
  cambio:
    description: Cambio pixelcoins/items
    usage: /<command>
  dinero:
    description: Comando para ver tu dinero
    usage: /<command>
  pagar:
    description: pagar dinero a otro nombreAccionista
    usage: /<command> <nombre nombreAccionista> <cantidad>
  normas:
    description: Ver las normas del servidor
    usage: /<command>
  deudas:
    description: Comandos relacionados con las empresas
    usage: /<command> <subComandos...>
  jugar:
    description: Ver comandos de jugadr
    usage: /<command>
  top:
    description: Ver a los jugadores que te deben y los que debes
    usage: /<command>
  tienda:
    description: mostrar la tienda de objetos
    usage: /<command>
  mensajes:
    description: ver todos los mensajes pendientes
    usage: /<command>
  empresas:
    description: comandos relacionados con la empresas
    usage: /<command> <subcommands...>
  cls:
    description: Limpiar el chat
    usage: /<command>
  ayuda:
    description: ver las ayudas
    usage: /<command>
  bolsa:
    description: comando relacionado con los comandos de la bolsa
    usage: /<command> <subComandos...>
  perfil:
    description: ver tu perfil
    usage: /<command>
  venderjugador:
    description: vender un objeto a un nombreAccionista
    usage: /<command> <nombreAccionista> <precio>
