package es.serversurvival.nfs.transacciones.mySQL;

public enum TipoTransaccion {
    BASEDATOS_CAMBIAR_NOMBRE,

    TIENDA_VENTA,

    JUGADOR_PAGO_MANUAL,
    JUGADOR_VENDER,

    WITHERS_INGRESAR,
    WITHERS_SACAR,
    WITHERS_SACARMAX,

    EMPRESA_BORRAR,
    EMPRESA_DEPOSITAR,
    EMPRESA_SACAR,
    EMPRESA_VENTA,
    EMPRESA_PAGAR_SALARIO,
    EMPRESA_COMPRAR_SERVICIO,
    EMPRESA_COMPRA_ACCION_EMPRESA,
    EMPRESA_COMPRA_ACCION_JUGADOR,
    EMPRESA_DIVIDENDO_ACCION,

    DEUDAS_PAGAR_CUOTA,
    DEUDAS_PRIMERA_TRANSFERENCIA,
    DEUDAS_PAGAR_TODADEUDA,

    BOLSA_COMPRA,
    BOLSA_CORTO_VENTA,
    BOLSA_CORTO_COMPRA,
    BOLSA_VENTA,
    BOLSA_DIVIDENDO,
    
    WEB_TRANSFERENCIA,
    WEB_COMPRAACCION,
    WEB_VENTA_ACCION,
    WEB_PAGAR_DEUDA,
    WEB_BORRAR_EMPRESA,
    WEB_CREAR_EMPRESA
}
