package es.serversurvival.pixelcoins.config._shared.domain;

public enum ConfigurationKey {
    MENSAJES_MAXIMO_TIEMPO_LEIDO_MS,
    TIENDA_MARCA_DE_AGUA,
    WEB_ACTIONS_SERVER_IP,
    WEB_ACTIONS_FRONTEND_SERVER_PORT,
    WEB_ACTIONS_BACKEND_SERVER_PORT,
    WEB_ACTIONS_SECRET_KEY,
    EMPRESAS_N_ACCIONES_INICIAL,
    EMPRESAS_VOTACION_TIME_OUT,
    EMPRESAS_PORCENTAJE_ACCIONES_TOTALES_VOTACION,
    FINHUB_API_KEY,
    BOLSA_PRECIOS_CACHE_N_VECES_LECTURA_SIN_ACTUALIZAR,
    BOLSA_PRECIOS_CACHE_TIEMPO_MS_VALIDOS,

    BOLSA_PREMARKET_HABILITADO,

    JUGADORES_CAMBIO_LAPISLAZULI,
    JUGADORES_CAMBIO_DIAMANTE,
    JUGADORES_CAMBIO_CUARZO,

    LOOTBOX_PRECIO_COMUN,
    LOOTBOX_PRECIO_NORMAL,
    LOOTBOX_PRECIO_RARO,

    PRINT_COMMANDS_EXCEPTIONS,

    SCOREBOARDS_N_TOP_JUGADORES,

    TPA_TIMEOUT_MS
}
